Fix Nix flake: use pkgs.spark instead of pkgs.apacheSpark
The attribute 'apacheSpark' doesn't exist in nixpkgs. The correct
attribute name is 'spark'.

Error was:
  error: attribute 'apacheSpark' missing at nix/flake.nix:67:23

This fixes the Build Cache failure.